src/OneStepTowardsChange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from OneStepTowardsChange.views import home
urlpatterns = [
    path('', home , name='ProjectHome'),
    path('publicnews/', include('publicnews.urls')),
    path('yojna/', include('yojna.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG :
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/publicnews/urls.py
from django.urls import path
from .views import publicnewshome


app_name = 'PublicNews'

urlpatterns = [
    
    path('home/', publicnewshome, name='PublicNewsHome'),
]

src/yojna/urls.py
from django.urls import path
from .views import yojnahome
app_name = 'Yojna'

urlpatterns = [
    
    path('home/', yojnahome, name='YojnaHome'),
]

src/yojna/models.py
from django.db import models

# Create your models here.

src/OneStepTowardsChange/views.py
from django.http import HttpResponse
from django.shortcuts import render 

def home(request):
    context = {
        
    }
    
    return render(request, 'home_page.html',context)

src/publicnews/views.py
from django.shortcuts import render

# Create your views here.
def publicnewshome(request):
    return render(request, 'publicnews/publicnews_home.html', {})

src/yojna/views.py
from django.shortcuts import render

# Create your views here.
def yojnahome(request):
    return render(request, 'yojna/yojna_home.html', {})

src/publicnews/templates/publicnews/publicnews_home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}OneStep - PublicNews{% endblock title %}
{% block content %}
<h1>This is Public News Home</h1>
{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% include 'base/css.html' %}
  <style>  {% block custom_css %}{% endblock custom_css %} </style>
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
  {% include 'base/navbar.html' %}
    {% block content %} {% endblock content %}

    {% block custom_js %}{% endblock custom_js %}
    {% include 'base/js.html' %}
  </body>
</html>

src/templates/base/css.html
 {% load static %}


      <!-- Fontawesome CSS -->
   <link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'/>
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,600,700,700i&amp;subset=latin-ext" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/fontawesome-all.css' %}
" rel="stylesheet">
    <link href="{% static 'css/swiper.css' %}
" rel="stylesheet">
      <link href="{% static 'css/magnific-popup.css' %}     
" rel="stylesheet">
	  <link href="{% static 'css/styles.css' %}     
" rel="stylesheet">

src/templates/base/js.html
{% load static %}

    <script>
      document.addEventListener('DOMContentLoaded', () => {

// Get all "navbar-burger" elements
const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

// Check if there are any navbar burgers
if ($navbarBurgers.length > 0) {

  // Add a click event on each of them
  $navbarBurgers.forEach( el => {
    el.addEventListener('click', () => {

      // Get the target from the "data-target" attribute
      const target = el.dataset.target;
      const $target = document.getElementById(target);

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      el.classList.toggle('is-active');
      $target.classList.toggle('is-active');

    });
  });
}

});
      </script>

    <script src="https://kit.fontawesome.com/ef5547766a.js" crossorigin="anonymous"></script> 

   <!-- Scripts -->

    <script src="   {% static 'js/jquery.min.js' %}
"></script> <!-- jQuery for Bootstrap's JavaScript plugins -->
    <script src="   {% static 'js/popper.min.js' %}
"></script> <!-- Popper tooltip library for Bootstrap -->
    <script src="   {% static 'js/bootstrap.min.js' %}
"></script> <!-- Bootstrap framework -->
    <script src="   {% static 'js/jquery.easing.min.js' %}
"></script> <!-- jQuery Easing for smooth scrolling between anchors -->
    <script src="   {% static 'js/swiper.min.js' %}
"></script> <!-- Swiper for image and text sliders -->
    <script src="   {% static 'js/jquery.magnific-popup.js' %}
"></script> <!-- Magnific Popup for lightboxes -->
    <script src="   {% static 'js/validator.min.js' %}
"></script> <!-- Validator.js - Bootstrap plugin that validates forms -->
    <script src="   {% static 'js/scripts.js' %}
"></script> <!-- Custom scripts -->

src/templates/base/navbar.html
{% load static %}
{% url 'ProjectHome' as projecthome_url %}
{% url 'Yojna:YojnaHome' as yojnahome_url %}
{% url 'PublicNews:PublicNewsHome' as publicnewshome_url %}

<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
  <!-- Text Logo - Use this if you don't have a graphic logo -->
  <!-- <a class="navbar-brand logo-text page-scroll" href="index.html">Evolo</a> -->

  <!-- Image Logo -->
  <a class="navbar-brand logo-image" href="second_layout.html"><h4>GrowIndia</h4></a>
  
  <!-- Mobile Menu Toggle Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-awesome fas fa-bars"></span>
      <span class="navbar-toggler-awesome fas fa-times"></span>
  </button>
  <!-- end of mobile menu toggle button -->

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav ml-auto">
          <li class="nav-item">
              <a class="nav-link page-scroll" href="#header">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
              <a class="nav-link page-scroll" href="#services">Services</a>
          </li>
          <li class="nav-item">
              <a class="nav-link page-scroll" href="#">Trending</a>
          </li>
          <li class="nav-item">
              <a class="nav-link page-scroll" href="#request">Join Us As Professional</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#contact">Contact</a>
        </li>
          <!-- Dropdown Menu -->          
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle page-scroll" href="#about" id="navbarDropdown" role="button" aria-haspopup="true" aria-expanded="false">More</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#"><span class="item-text">One</span></a>
                  <div class="dropdown-items-divide-hr"></div>
                  <a class="dropdown-item" href="#"><span class="item-text">Two</span></a>
                  <div class="dropdown-items-divide-hr"></div>
                  <a class="dropdown-item" href="#"><span class="item-text">Three</span></a>
                  <div class="dropdown-items-divide-hr"></div>
                  <a class="dropdown-item" href="#"><span class="item-text">Four</span></a>
                  <div class="dropdown-items-divide-hr"></div>
                  <a class="dropdown-item" href="#"><span class="item-text">Five</span></a>
              </div>
          </li>
          <!-- end of dropdown menu -->

          
      </ul>
      <span class="nav-item social-icons">
          <span class="fa-stack">
              <a href="#your-link">
                  <i class="fas fa-circle fa-stack-2x facebook"></i>
                  <i class="fab fa-facebook-f fa-stack-1x"></i>
              </a>
          </span>
          <span class="fa-stack">
              <a href="#your-link">
                  <i class="fas fa-circle fa-stack-2x twitter"></i>
                  <i class="fab fa-twitter fa-stack-1x"></i>
              </a>
          </span>
      </span>
  </div>
</nav> <!-- end of navbar -->

src/yojna/templates/yojna/yojna_home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}OneStep - Yojna's{% endblock title %}
{% block content %}
<h1>This is Yojna Home</h1>
{% endblock content %}